ant-design-blazor/blazor-pro-components

- example/AntDesign.Pro.Layout.Wasm/Components/Footer.razor
- example/AntDesign.Pro.Layout.Wasm/Shared/ProLayout.razor
- src/BasicLayout.razor
- src/Core/AntProComponentBase.cs
Layout component can't set custom footer component.
> fix(module: footer): unable to set footer

- .gitignore
- example/AntDesign.Pro.Layout.Wasm/Shared/ProLayout.razor
- src/AntDesign.Pro.Layout.csproj
- src/BasicLayout.razor
- src/BasicLayout.razor.cs
- src/GlobalHeader/GlobalHeader.razor
- src/GlobalHeader/GlobalHeader.razor.cs
- src/HeaderDropdown/HeaderDropdown.less
- src/HeaderSearch/HeaderSearch.razor
- src/HeaderSearch/HeaderSearch.razor.cs
- src/HeaderSearch/HeaderSearch.razor.less
- src/NoticeIcon/NoticeIcon.razor
- src/NoticeIcon/NoticeIcon.razor.cs
- src/NoticeIcon/NoticeIcon.razor.less
- src/NoticeIcon/NoticeIconData.cs
- src/NoticeIcon/NoticeList.razor
- src/NoticeIcon/NoticeList.razor.cs
- src/NoticeIcon/NoticeList.razor.less
- src/PageContainer/PageContainer.razor
- src/PageContainer/PageContainer.razor.cs
- src/RightContent/AvatarDropdown.razor
- src/RightContent/AvatarDropdown.razor.cs
- src/RightContent/RightContent.razor
- src/RightContent/RightContent.razor.cs
- src/RightContent/RightContent.razor.less
- src/SelectLang/SelectLang.razor
- src/SelectLang/SelectLang.razor.cs
- src/SelectLang/SelectLang.razor.less
- src/SettingDrawer/SettingDrawer.razor.cs
components:
1.HeaderSearch
2.AvatarDropdown
3.SelectLang
4.NoticeIcon [WIP]
5.RightContent
remark:
1.AutoComplete component missing ant style, and broken in pro project,.
2.Dropdown overlay style not working.
...
> feat(module: GlobalHeader): add new components

- src/BasicLayout.razor
- src/PageContainer/PageContainer.razor
- src/PageContainer/PageContainer.razor.cs
1.fix pagecontainer missing extra property
2.fix error style
> fix(module: pagecontainer) missing extra property

- src/NoticeIcon/NoticeList.razor
- src/PageContainer/PageContainer.razor
- src/PageContainer/PageContainer.razor.cs
- src/PageContainer/TabPaneItem.cs
- src/SiderMenu/BaseMenu.razor
> feat(module: pagecontainer) add tab

- src/NoticeIcon/NoticeList.razor
- src/SettingDrawer/LayoutSetting.razor
- src/SettingDrawer/OtherSetting.razor
- src/SettingDrawer/RegionalSetting.razor
fix broken components after updating to the latest version.
> sync to 0.4.0-nightly-2009170319

- src/NoticeIcon/NoticeIcon.razor
- src/NoticeIcon/NoticeIcon.razor.cs
fix ant-design-blazor/ant-design-pro-blazor#43
> [fix](module: noticelist) dropdown can not be closed

- src/BasicLayout.razor.cs
- src/SiderMenu/SiderMenu.razor
- src/SiderMenu/SiderMenu.razor.cs
- src/TopNavHeader/TopNavHeader.razor.cs
fix ant-design-blazor/ant-design-pro-blazor#45
> [fix](module: sidermenu) collapse button always highlight

- example/AntDesign.Pro.Layout.Wasm/Shared/ProLayout.razor
- src/SettingDrawer/LayoutSetting.razor
sync to 0.5.0-nightly-2011270522
> [fix](module: layout) incorrect usage of select

- src/layout/src/SiderMenu/BaseMenu.razor
- src/layout/src/SiderMenu/MenuDataItem.cs
> add navlinkmatch attribute

- src/layout/src/BasicLayout.razor
- src/layout/src/BasicLayout.razor.cs
> fix: BasicLayout. OnCollapse event callback not invoked

- src/layout/src/NoticeIcon/NoticeList.razor
- src/layout/src/NoticeIcon/NoticeList.razor.cs
fixed ant-design-blazor/ant-design-pro-blazor/issues/83
> add item click event callback for notice list

- src/layout/src/SiderMenu/BaseMenu.razor
> fix missing HideInMenu for sider menu item

- src/layout/src/BasicLayout.razor.cs
- src/layout/src/SiderMenu/SiderMenu.razor.cs
fixed https://github.com/ant-design-blazor/ant-design-pro-blazor/issues/91#issue-955575853
> fix null reference exception

- src/layout/src/BasicLayout.razor
Use SiderWidth of BasicLayout to set SiderWidth of SiderMenu
> fix(BasicLayout): SiderWidth of SiderMenu

- src/layout/src/BasicLayout.razor
- src/layout/src/BasicLayout.razor.cs
- src/layout/src/SiderMenu/SiderMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor.cs
> Added parameter to logo href URL

- src/layout/src/Core/AntProComponentBase.cs
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3201
> fix Dispatcher execution error

- src/layout/src/RightContent/AvatarDropdown.razor
When avatar is null or empty showing user icon looks better.
> Update AvatarDropdown for showing user icon when avatar is empty

- src/layout/src/AntDesign.ProLayout.csproj
- src/layout/src/BasicLayout.razor
- src/layout/src/BasicLayout.razor.cs
- src/layout/src/SiderMenu/BaseMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor.cs
> fix(BasicLayout): Invalid setting collapsed value

- src/layout/src/AntDesign.ProLayout.csproj
- src/layout/src/SiderMenu/SiderMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor.cs
fixed https://github.com/ant-design-blazor/blazor-pro-components/issues/77
> Fix layout collapse

- src/layout/example/AntDesign.ProLayout.Wasm/Shared/ProLayout.razor
- src/layout/src/BasicLayout.razor
- src/layout/src/BasicLayout.razor.cs
- src/layout/src/SiderMenu/BaseMenu.razor
- src/layout/src/SiderMenu/BaseMenu.razor.cs
- src/layout/src/SiderMenu/SiderMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor.cs
- src/layout/src/TopNavHeader/TopNavHeader.razor.cs
> feat(SiderMenu): support two-way bingding for OpenKeys

- src/layout/example/AntDesign.ProLayout.Wasm/Shared/ProLayout.razor
- src/layout/src/BasicLayout.razor
- src/layout/src/BasicLayout.razor.cs
- src/layout/src/SiderMenu/BaseMenu.razor
- src/layout/src/SiderMenu/BaseMenu.razor.cs
- src/layout/src/SiderMenu/SiderMenu.razor
- src/layout/src/SiderMenu/SiderMenu.razor.cs
- src/layout/src/TopNavHeader/TopNavHeader.razor.cs
> feat: add OnMenuItemClicked,SelectedKeys,SelectedKeysChanged

- .gitignore
- src/layout/src/AntDesign.ProLayout.csproj
- src/layout/src/SettingDrawer/SettingDrawer.razor
Update AntDesign 0.20.3, And Fix the SettingDrawer  Width Bug.
> Update AntDesign 0.20.3, And Fix the SettingDrawer  Width Bug.
